### ISSUE TITLE
expose more functions from rust SDK

### ISSUE THREAD

**Issue by wakamex** [delvtech/agent0#1010]
things that would be useful for me right now:

- get_bonds_out_for_shares_in
- get_shares_out_for_bonds_in
- get_bonds_in_for_shares_out
- get_shares_in_for_bonds_out

please put your suggestions below.

**Comment by dpaiton** [comment]
These are all private functions in the `yieldspace.rs` library. What is the use case for making them public?

**Comment by wakamex** [comment]
should we add something like the `measure_value` function used here? https://github.com/delvtech/agent0/pull/1352/files#diff-588ee93bc3288ed7ed17a880e6ffdda7c986c72d22d289b23fbef3e2e0c07a4bR42

**Comment by wakamex** [comment]
this predict function definitely feels like it should be in the rust SDK because it's very low-level https://github.com/delvtech/agent0/blob/a317f3d2fd0ece2627814a7d2368d6c87c52e9e4/src/agent0/core/hyperdrive/utilities/predict.py

**Comment by dpaiton** [comment]
closing in favor of https://github.com/delvtech/agent0/issues/1514
