### ISSUE TITLE
create test for accuracy of: 1) predicting outcome of trade 2) hitting target rate

### ISSUE THREAD

**Issue by wakamex** [delvtech/agent0#1015]
known inaccuracies:
- share_price will be different on the next block. can try to estimate the one block return with something like `one_block_return = (FixedPoint(1) + variable_rate) ** (FixedPoint(12) / FixedPoint(365 * 24 * 60 * 60)`

**Comment by wakamex** [comment]
known inaccuracies:
- share_price will be different on the next block. can try to estimate the one block return with something like `one_block_return = (FixedPoint(1) + variable_rate) ** (FixedPoint(12) / FixedPoint(365 * 24 * 60 * 60)`

**Comment by wakamex** [comment]
consider the right tolerance threshold https://github.com/delvtech/elf-simulations/pull/1000#discussion_r1363116004

**Comment by wakamex** [comment]
is there another factor to improve the speed of convergence? https://github.com/delvtech/elf-simulations/pull/1000#discussion_r1363014016

**Comment by dpaiton** [comment]
Resolved by #1078
