### ISSUE TITLE
Clean up database interface wrt interactive hyperdrive

### ISSUE THREAD

**Issue by slundqui** [delvtech/agent0#1106]
Implementing the interactive hyperdrive has exposed various issues surrounding the data in the database, especially in the context of a user facing interface for the data. Below is a few issues found:

- Checkpoint info table seems to be bugged, perhaps due to accelerated time
- Current wallet only stores the final base delta (e.g., -1000 base from the starting value), not the absolute value. While this is nice for the dashboard, the interface should report actual base amount in wallet over time.
- A lot of current tables (e.g., current wallet, wallet pnl, wallet positions over time) that report current positions ignore zero values, so we don't see the positions when someone closes all longs. Fix.

There is also some light postprocessing that would help with interacting with the data. For example, current wallet reports data as a rows with the token types stored in a column, where it would be more intuitive to pivot the table so that token types are columns.

**Comment by slundqui** [comment]
Most of these issues are solved in https://github.com/delvtech/agent0/pull/1110. However, the checkpoint info bug still exists in conjunction with advancing time. The issue here is that we don't mint checkpoints when advancing time, and hence, the checkpoint info table is bugged.

**Comment by dpaiton** [comment]
implemented in #1110
