### ISSUE TITLE
fuzzing: add invariant tests in fuzz pipeline

### ISSUE THREAD

**Issue by dpaiton** [delvtech/agent0#1123]
These issues
https://github.com/delvtech/hyperdrive/issues/253
https://github.com/delvtech/hyperdrive/issues/534

outline a list of "invariants" (assumed truths) that should hold in hyperdrive at any time.

We've sorted them into two categories:
1. Alongside fuzz testing -- After each block is mined these invariants will be checked using the stored database state values inside a parallel cron job
2. Using interactive hyperdrive -- These are not using the fuzz framework, but instead are targeted tests using a controlled set of trades

---------------------------

1.  Invariants to check alongside fuzz trades:
- [x] total shares == share reserves + shorts outstanding/c + _governanceFeesAccrued + _withdrawalPool.proceeds + epsilon
- [x] the system should always be solvent (solvency = share_reserves - global_exposure - minimum_share_reserves > 0)
- [x] PV always >= idle
- [x] ∆ lp share price should never be more than 0.1%
- [x] share reserves * c - long exposure >= minimum share reserves
- [x] creating a checkpoint should never fail

2. Conditions to check in an interactive setting (aka static tests; not included in fuzz testing)
- [x] opening and immediately closing a trade shouldn't result in profit
- [x] longs and shorts should always be closed at maturity for the correct amounts
- [x] given a set of open positions, the final state of the reserves will be the same no matter what order the positions are closed in (path independence).
- [x] if all of the funds are removed from Hyperdrive, there is no base left in the contract

Present value interactive test
do all trades (add & remove liquidity, open & close longs & shorts)
- [x] For any trade, LP share price (which = present value / number of shares) shouldn't change by more than 0.1% when distributing excess idle (which is called when any action is done)
- [x] open or close trades shouldn't affect PV (within tolerance, maybe 0.1%?)
- [x] removing liquidity shouldn't result in the PV increasing (it should decrease)
- [x] adding liquidity shouldn't result in the PV decreasing (it should increase)
- [x] PV always >= idle

**Comment by dpaiton** [comment]
Input from @jalextowle 

> What I'm looking for is for us to fuzz invariants by making random actions and checking a set of invariants between every action. You can find a list of the invariants that we want to fuzz here: https://github.com/delvtech/hyperdrive/issues/534 and https://github.com/delvtech/hyperdrive/issues/253. If we get that finished, maybe working on automating crash reporting and deployment is useful, but we should start manual and only consider automation once we are getting real bug reports. Aside from that, I don't think that we should spend any time making the fuzzing smarter until we get to a point where we can't find bugs without it (i.e. we've spent a day or two fuzzing and we haven't found anything). Everything should be driven by breaking invariants and how long it takes the system to do so.

**Comment by dpaiton** [comment]
These are the checks in the second category:

```
opening and immediately closing a trade shouldn't result in profit
 
given a set of open positions, the final state of the reserves will be the same no matter what order the positions are closed in (path independence).
 
if all of the funds are removed from Hyperdrive, there is no base left in the contract
 
LP share price shouldn't change by more x% when distributing excess idle
 
trades are never executed with negative interest rates
```

This category isn't to say that there is no fuzzing element, just to say that it is not part of the fuzz bot workflow. Each of them has its own explanation, but broadly I think the idea is these things are explicit situations that wouldn't necessarily come up by running a random trading bot. In other words, each of them assumes we're setting up some contrived state and checking a condition, instead of checking the condition after any random state.

opening and immediately closing a trade shouldn't result in profit -- the likelihood of a random bot opening & closing a trade immediately is low; we should have a notebook that fuzzes the amount, but explicitly does this open-then-close workflow and checks the profit amounts

given a set of open positions, the final state of the reserves will be the same no matter what order the positions are closed in (path independence) -- we randomly open some positions, save state, then in a loop close them at random, then check reserve levels

if all of the funds are removed from Hyperdrive, there is no base left in the contract -- we randomly open positions, then close them all, then check base balance

LP share price shouldn't change by more x% when distributing excess idle -- we set up scenarios with random LP shares & idle, and then check share price changes during distribution

trades are never executed with negative interest rates -- we execute all possible trades (with random values) with a negative rate and confirm that it never is executed

**Comment by dpaiton** [comment]
#1138 #1161 #1162

**Comment by dpaiton** [comment]
Opened issues can be found here: https://github.com/delvtech/hyperdrive/issues?q=is%3Aissue+label%3Apython+

**Comment by slundqui** [comment]
After https://github.com/delvtech/agent0/pull/1231, we have the following left:

> [ ]  update base budget to 100% of liquidity, so that max trades could cause large swings
> we might need to add some sort of weighting to the random draw so that super large trades are unlikely, or we could have a checker that monitors the pool state and adjusts it (e.g. launch the lp_and_arb bot alongside random bots & give it a large tolerance).

Holding off for now to test if previous crashes is fixed in version v0.4.0

> [ ] line 93: Guarantee that the closing trades are all within the same checkpoint. Could we force these to the same block? Alex suggested that we should be able to stop the "mine per transaction" anvil process, close the trades, mine a block, and then start it back up again. Either way, it should be implemented in helpers/close_random_trades.py with a flag on_single_block: bool =False

Implementing feature in follow up PR

> [ ] line 101: present value should also match within tolerance (maybe 1e15 to 1e18, bc of weighted average & rounding)

Waiting for present value checks to be written

> [ ]  line 252: verify that the effective share reserves check is valid now that we have zombie shares

Took a quick look, calculating effective share reserves doesn't have zombie shares in the rust sdk. Need to dig deeper.

**Comment by slundqui** [comment]
>  line 65: advance_time should be False & no trades should mature
the total time advanced after open_random_trades() should be less than first trade's position duration

Revisiting, such that advance time is now True for this, and open_random_trades doesn't pass a position duration for the first trade
https://github.com/delvtech/agent0/pull/1232

**Comment by dpaiton** [comment]
Adding descriptions to make the tests easier to grok here https://github.com/delvtech/agent0/pull/1233

**Comment by dpaiton** [comment]
Additional todos:
- [ ] modify max amount in `open_random_trades` to use max_long and max_short instead of hard-coding 100k

**Comment by slundqui** [comment]
>  refactor long_short_maturity test:
assert open bonds == close bonds, then just use one of them (instead of testing both)
verify close vs open base amounts, are we using the correct ones? Remove intermediate variables and instead add comments noting why we're using open vs close.
verify that the TODO on line 117 (ensure maturity chkpt is maturity of all positions) is done, delete it
https://github.com/delvtech/agent0/pull/1234

**Comment by dpaiton** [comment]
>   line 101: present value should also match within tolerance (maybe 1e15 to 1e18, bc of weighted average & rounding)

https://github.com/delvtech/agent0/pull/1236

**Comment by dpaiton** [comment]
> random policy uses min transaction amount for trade lower bound

https://github.com/delvtech/agent0/pull/1238

**Comment by dpaiton** [comment]
>  modify max amount in generate_trade_list to use max_long and max_short instead of hard-coding 100k

https://github.com/delvtech/agent0/pull/1241

**Comment by slundqui** [comment]
>  add a flag to make variable interest zero (this is just in config right?)

https://github.com/delvtech/agent0/pull/1242

**Comment by slundqui** [comment]
> line 93: Guarantee that the closing trades are all within the same checkpoint. Could we force these to the same block? Alex suggested that we should be able to stop the "mine per transaction" anvil process, close the trades, mine a block, and then start it back up again. Either way, it should be implemented in helpers/close_random_trades.py with a flag on_single_block: bool =False

We added assertions for the path independence test to ensure transactions are closed within the same checkpoint (https://github.com/delvtech/agent0/pull/1242). However, it's a bit of a heavy lift to add the feature for multiple transactions on the same block for interactive hyperdrive, mostly due to keeping everything synchronous in interactive hyperdrive. This feature is detailed in https://github.com/delvtech/agent0/issues/1244, but we're working around this for now by turning off variable interest for the path independence test.

**Comment by dpaiton** [comment]
TODOs after latest convo

- [ ] in our fuzz tests lets prevent allowing two max longs/shorts in row
- [ ] set it to use 75% of the max long
- [ ] add an issue to catch neg interest in crash reporting and see if it's because max long was too big (calc_max has noise, this results from two max trades in a row)
- [ ] add new time stretch calc to rust & hyperdrivepy
- [ ] path_independence_check effective share reserves has tolerance of 1e-4
- [ ] instead of making trades close on same block lets just set variable rate to 0 right before you start closing (we can do this in `close_random_trades.py`)

**Comment by slundqui** [comment]
>  set it to use 75% of the max long

> path_independence_check effective share reserves has tolerance of 1e-4

> instead of making trades close on same block lets just set variable rate to 0 right before you start closing (we can do this in close_random_trades.py)

> delete hyperdrive balance test (this test only works if closures happen on same block, which we can't do)

https://github.com/delvtech/agent0/pull/1249

**Comment by dpaiton** [comment]
new TODOs:

- [ ] increase the number of times we run the test
- [ ] if a closure path fails (neg interest, over/under flow); skip that closure path
  - if none of the paths succeed, skip the test
  - make sure you log those errors, but don't count it as a failed test
- [ ] only count the fuzz test as "failed" if we had >1 successful close path AND the invariance checks failed.

**Comment by slundqui** [comment]
> increase the number of times we run the test
> if a closure path fails (neg interest, over/under flow); skip that closure path
>     if none of the paths succeed, skip the test
>     make sure you log those errors, but don't count it as a failed test
> only count the fuzz test as "failed" if we had >1 successful close path AND the invariance checks failed.

https://github.com/delvtech/agent0/pull/1252

**Comment by slundqui** [comment]
> check that we have a test that closes random trades at maturity in random orders, and we expect them to never fail (e.g. neg interest)

https://github.com/delvtech/agent0/pull/1253

**Comment by dpaiton** [comment]
>  update base budget to 100% of liquidity, so that max trades could cause large swings
we might need to add some sort of weighting to the random draw so that super large trades are unlikely, or we could have a checker that monitors the pool state and adjusts it (e.g. launch the lp_and_arb bot alongside random bots & give it a large tolerance).
 larger slippage tolerance (maybe 10%? or better yet randomly on/off for each bot) to allow big trades
 
 achieved in https://github.com/delvtech/agent0/pull/1265

**Comment by dpaiton** [comment]
Closing this issue as all tasks have been completed.
