### ISSUE TITLE
Web3 is throwing a warning for mismatched event ABIs when decoding logs

### ISSUE THREAD

**Issue by slundqui** [delvtech/agent0#1130]
Narrowed down to `GovernanceUpdated` event from calling `deployAndInitialize` in factory. Suppressing warning for now.

https://github.com/delvtech/agent0/blob/20aa00d5847de8bf9569e10f0aa156320c577444/lib/ethpy/ethpy/base/receipts.py#L79

**Comment by dpaiton** [comment]
transaction receipt can contain multiple events (e.g. in initialize). We're only looking at contract events, but the events could come from other contracts.

**Comment by dpaiton** [comment]
closing bc we are handling the problem (only filtering for relevant receipt attributes) and suppressing the warning.
