### ISSUE TITLE
clean up feature flags in interactive hyperdrive

### ISSUE THREAD

**Issue by wakamex** [delvtech/agent0#1237]
Based on the discussion in #1207 we're allowing the addition of new feature flags for the moment.

At a future point, we may want to circle back and re-structure things to remove them, if they become too unwieldy.

For the moment, the main feature toggle is `calc_pnl` which disables the calculation of PNL during the simulation, to allow for faster simulations that don't require pnl calculation until the end (if ever).

**Comment by dpaiton** [comment]
We have a general opinion to reduce feature flags whenever possible. So there's no need to keep this as an issue.
