### ISSUE TITLE
Set interactive hyperdrive dot directories to be unique per chain/pool

### ISSUE THREAD

**Issue by slundqui** [delvtech/agent0#1264]
Interactive hyperdrive uses two places to store files, namely `.interactive_state` and `.crash_report`. In the case where we run multiple chains, these files can conflict with each other, overwriting files. Need to update these directory paths based on a unique chain identifier to prevent this. An existing chain identifier already is being used for the postgres docker container (named `formatted_rpc_url`), so likely can reuse this identifier for the above directories.

**Comment by wakamex** [comment]
I'm fine as is since each run is executed from its own directory, so they have their own `.interactive_state` and `.crash_report` sub-folders.

**Comment by slundqui** [comment]
Keeping `.crash_report` as is, as it's not explicit to the chain object. Here, each crash report is indexed by time + random number to avoid conflicts.

The `.interactive_state` issue was fixed during the refactor.
