### ISSUE TITLE
fuzz testing action items

### ISSUE THREAD

**Issue by dpaiton** [delvtech/agent0#1269]
- [x] for max_short error with random fuzz bots
  - baller bots: adjust fuzz bots to always have a big enough budget to be much more than the pool reserves
- [x] add calculate_idle_share_reserves to hyperdrive, sdk, & hyperdrive interface
- [x] pv test for add/remove liquidity test, we need to re-compute initial present value bc adding moves it so we need a new initial
- [x] audit all of the test descriptions again; verify that they are correct and that they note whether or not there are fees
- [x] add a better description to all of the error messages so we can see what was expected to happen from rollbar
- [x] path independence
  - change "share price" to "lp share price"
- [x] long/short maturity values: expected values on shorts is off. need to dive in
- [x] Open/close long/short shouldn't make money (jonny needs to repro in solidity)
- [x] update continuous fuzz bot vault share check to use a new formula from Jonny

**Comment by slundqui** [comment]
> for max_short error with random fuzz bots
>    baller bots: adjust fuzz bots to always have a big enough budget to be much more than the pool reserves

Fuzz bots had much less base than expected due to bugs in agent0, fixed in https://github.com/delvtech/agent0/pull/1270

**Comment by slundqui** [comment]
>  long/short maturity values: expected values on shorts is off. need to dive in

Updated relevant issue with new crash report from v0.5.1
https://github.com/delvtech/hyperdrive/issues/698

**Comment by slundqui** [comment]
>  path independence
> change "share price" to "lp share price"

https://github.com/delvtech/agent0/pull/1272

**Comment by dpaiton** [comment]
>  add calculate_idle_share_reserves to hyperdrive, sdk, & hyperdrive interface
made a separate issue for this https://github.com/delvtech/agent0/issues/1276

**Comment by dpaiton** [comment]
> pv test for add/remove liquidity test, we need to re-compute initial present value bc adding moves it so we need a new initial

https://github.com/delvtech/agent0/pull/1275

**Comment by dpaiton** [comment]
>  audit all of the test descriptions again; verify that they are correct and that they note whether or not there are fees

https://github.com/delvtech/agent0/pull/1273

**Comment by slundqui** [comment]
> Open/close short shouldn't make money (jonny needs to repro in solidity)

Reproduced, the cause is the variable rate, there's 12 seconds between the open/close short, which without fees, the short itself will make money. Confirmed by reducing the amount of time between open/short to 1 second, and the short made less money. Solidity roundtrip tests within a checkpoint assumes 0% interest.

**Comment by jrhea** [comment]
> Open/close long/short shouldn't make money (jonny needs to repro in solidity)

opened issue [#739](https://github.com/delvtech/hyperdrive/issues/739) to track. tl;dr this is a known issue and a result of sharePrice inaccuracy.

**Comment by dpaiton** [comment]
Closing -- these issues have been addressed or tabled.
