### ISSUE TITLE
Update to the generalized `vaultSharesToken` getter

### ISSUE THREAD

**Issue by jalextowle** [delvtech/agent0#1384]
Use `vaultSharesToken` instead of `vault`, `lido`, `ezETH`, etc.

**Comment by slundqui** [comment]
Solved via the following PRs:
https://github.com/delvtech/agent0/pull/1385
https://github.com/delvtech/agent0/pull/1387
https://github.com/delvtech/agent0/pull/1388

**Comment by dpaiton** [comment]
Closing since this is marked as Done.
