### ISSUE TITLE
Run LP and Arb bots on testnet

### ISSUE THREAD

**Issue by jalextowle** [delvtech/agent0#1389]
Run an LP and Arb bot to keep the network within a reasonable state. @wakamex To make a command decision on this (go to @CPSTL for Sepolia ETH).

**Comment by dpaiton** [comment]
You should find the changes here for checkpoint bot to be helpful https://github.com/delvtech/agent0/issues/1393

**Comment by wakamex** [comment]
running fine for a few days now. thanks to several supporting PRs:
- Connect and trade bots on steth pool (#1392)
- Adding sync interactive hyperdrive agent from chain api (#1401)
- add timeout to smart_contract_transact functions (#1402)
- make default timeout longer (#1404)
- add gas limit parameter to trade functions (#1406)
- Exposing wait for transaction receipt timeout to interactive hyperdrive (#1417)
- add gas price multiples (#1433)
