### ISSUE TITLE
Running a checkpoint bot on testnet

### ISSUE THREAD

**Issue by jalextowle** [delvtech/agent0#1390]
We're going to want checkpoint bots targeting each pool (there will be 4 pools).

**Comment by dpaiton** [comment]
should be resolved by https://github.com/delvtech/agent0/issues/1393 but we will want to test again after the next round of releases.

**Comment by dpaiton** [comment]
Completed via 
https://github.com/delvtech/agent0/pull/1397
https://github.com/delvtech/agent0/pull/1400
