### ISSUE TITLE
Load Hyperdrive pool from any historical state

### ISSUE THREAD

**Issue by dpaiton** [delvtech/agent0#1410]
Unsure if this is better or worse than just [forking at a block](https://www.quicknode.com/guides/ethereum-development/smart-contracts/how-to-fork-ethereum-blockchain-with-foundry). But it might be useful to grab all events & deploy anvil + hyperdrive with initial config and then use chainsync to aggregate & replay all trades.

**Comment by dpaiton** [comment]
This is not required because we can do forking now. @slundqui is going to verify that forking allows us to get all events then close this issue.

**Comment by slundqui** [comment]
Verified, forking allows us to query events.
