### ISSUE TITLE
Generalize the fuzzing for ERC4626 and stETH

### ISSUE THREAD

**Issue by jalextowle** [delvtech/agent0#1420]
We should generalize the fuzzing for `ERC4626` and `stETH` by initializing the pools with more general initial conditions. In particular, we should fuzz over:

- [ ] The initial LPs contribution (we should also randomly remove this to test low-liquidity situations)
- [ ] The time stretch APR (we'll need to set the initial fixed APR equal to this to avoid problems)
- [ ] The variable APR

**Comment by dpaiton** [comment]
Closing since this is marked as Done.
