### ISSUE TITLE
Update chainsync to work with events

### ISSUE THREAD

**Issue by dpaiton** [delvtech/agent0#1453]
The functionality will be relatively unchanged at first, as this is an "under the hood" modification. However, it will unlock new features:
- add ability to boot into iHyperdrive from any chain block
- “replay history” feature & "backtesting"
- shift repo in the direction of a more general utility
- allow us to sync wallets more easily with a single utility

**Comment by slundqui** [comment]
Added via https://github.com/delvtech/agent0/pull/1464
