### ISSUE TITLE
Production Bots

### ISSUE THREAD

**Issue by jalextowle** [delvtech/agent0#1515]
1. [ ] Need a place where we write down bot machines
2. [ ] Where are credentials stored?
3. [ ] Make sure that we have funded accounts for mainnets and L2s
4. [ ] Monitoring?

**Comment by slundqui** [comment]
Rollbar would be a good choice for monitoring.

Discord notifications:
https://docs.rollbar.com/docs/sending-discord-notifications-using-webhooks-and-hookdeck

**Comment by slundqui** [comment]
This PR moves the service bots (i.e., checkpoint bot and invariance check bots) to docker that lives in infra.
https://github.com/delvtech/hyperdrive-infra/pull/118

**Comment by jrhea** [comment]
Is this task complete?  Seems like we have credential management, notifications and monitoring handled.
