### ISSUE TITLE
support stETH pools

### ISSUE THREAD

**Issue by dpaiton** [delvtech/agent0#1545]
- [x] local hyperdrive needs to deploy steth mock yield source & steth hyperdrive 
- [x] add a test that trades with steth & verifies balance correctness
- [x] update agent0 such that (under the hood) the bot checks the pool type and does proper conversions to/from shares if it is a rebasing token (steth) vs not (erc4626)

**Comment by slundqui** [comment]
Need to figure out priority of this task:
- A bit of a lift to rework agent0 to support rebasing tokens.
- Minimal change to accept only eth on steth markets, but not all trades are available (is this only for mock lido?)

Need this feature to (1) do trades and run bots on steth market on mainnet, and (2) run fuzz testing on steth market (not currently being done)

**Comment by slundqui** [comment]
https://github.com/delvtech/agent0/pull/1570 implements deploying steth and adding (breaking) test for checking balance correctness

**Comment by slundqui** [comment]
https://github.com/delvtech/agent0/pull/1571 gathers all event getters and definitions to ethpy interface

**Comment by slundqui** [comment]
https://github.com/delvtech/agent0/pull/1572 converts steth to/from lido shares before passing to contracts.

**Comment by slundqui** [comment]
Finished with PRs https://github.com/delvtech/agent0/pull/1570, https://github.com/delvtech/agent0/pull/1571, https://github.com/delvtech/agent0/pull/1572
