### ISSUE TITLE
get real underlying rate in get_market_state_from_contract

### ISSUE THREAD

**Issue by wakamex** [delvtech/agent0#414]
currently using a placeholder that needs to be removed: `variable_apr=0.01,  # TODO: insert real value`

**Comment by dpaiton** [comment]
HyperdriveInterface has this now https://github.com/delvtech/agent0/blob/69e077cedfd097794cc53ee631ccd6a70f14c6f3/lib/ethpy/ethpy/hyperdrive/interface/interface.py#L281
