### ISSUE TITLE
crash-reporting: monitor logs from python+anvil

### ISSUE THREAD

**Issue by wakamex** [delvtech/agent0#475]
create minimal docker service to observe logs from both python and anvil

**Comment by dpaiton** [comment]
I think the best path here is to grab the anvil logs and put them in our own .logging file, along with our own logs. Then one can use `tail` to locally view the latest lines from the remote file.

**Comment by dpaiton** [comment]
Closing this; doesn't seem to useful anymore. We can reopen if we decide we need it again.
