### ISSUE TITLE
crash-reporting: dump agent & python rng full state when bots go down

### ISSUE THREAD

**Issue by dpaiton** [delvtech/agent0#615]
store anvil & python rng state to file

* dev can re-create the problem & debug with  variable access
* we can reboot chain from wherever crash happened after fixing the bug (after issue #541 is completed)

**Comment by wakamex** [comment]
latest stored here: https://github.com/wakamex/elf-simulations/tree/state_dump

**Comment by dpaiton** [comment]
@slundqui added bot state in #1029 
need to add numpy rng as well

**Comment by dpaiton** [comment]
Might be obsolete after https://github.com/delvtech/agent0/issues/1411

**Comment by dpaiton** [comment]
This is a big lift, and it's easier to just fork from the block.
