### ISSUE TITLE
request: deterministic key generation in --develop mode

### ISSUE THREAD

**Issue by wakamex** [delvtech/agent0#809]
I love the automatic key generation for testing, so I don't have to think about it.

but it would be nice if they were repeatable, so my agents have the same address every time I run an experiment.

I already have a `MNEMONIC=` in my `.env` which could be a nice way to let a user determine their own random (but repeatable) sequence of keys, with the option of being different across experiments or users. and maybe in its absence, a random mnemonic could be generated, from which to sample?

**Comment by wakamex** [comment]
I like this example:
https://github.com/ethereum/eth-account/blob/6a7faa22c1c433422186bf792f870e4c04d59a08/eth_account/account.py#L117

**Comment by wakamex** [comment]
generating multiple public keys from 1 mnemonic!

https://github.com/ethereum/eth-account/blob/6a7faa22c1c433422186bf792f870e4c04d59a08/eth_account/account.py#L300C1-L310C45

**Comment by dpaiton** [comment]
Coupled with #816

**Comment by dpaiton** [comment]
The new agent0 flow supports assigning private keys, so you can deterministically generate them in your runner script. We also don't have `--develop` mode anymore.
