### ISSUE TITLE
request: write custom bots outside of the agent0 repo

### ISSUE THREAD

**Issue by wakamex** [delvtech/agent0#828]
as discussed below, writing experiments that use the bot testing framework outside of the agent0 repo is very desirable:
1. don't have to fork the repo (can just install the packages)
2. can save experiments and scripts in a repo separate from the elf-sims packages (I'll be using <https://github.com/delvtech/ro-bots> for this)
  - this achieves code separation and allows people to read and repeat experiments with minimal mental overhead

my feedback in discord of August 11th:
> i tested running bots by installing everything as a package. it's a bit janky because you can't install anything outside of the package. so i have to explicitly download `run_hyperdrive_agents` and the abi's, which is super janky (<https://github.com/delvtech/ro-bots/blob/master/setup.py>). also had to tweak config in two ways:
> - pass `args` as an argument, in lieue of using a command-line argument (`--develop`)
<https://github.com/delvtech/elf-simulations/commit/6805d78ec22b62e049a43cc92b10f9e1adaff775>
> - allow overriding config variables without changing the code
<https://github.com/delvtech/elf-simulations/commit/12f1416e4c497c00dc176ec1bc91e0ecafa70e61>

mention by @slundqui in #826:
> Prerequisite for writing custom bots outside of the agent0 repo

**Comment by dpaiton** [comment]
This is something we want, but will need some discussion on how it should be implemented before we take action.

**Comment by dpaiton** [comment]
We can do this roughly by:
```py
import agent0

cass my_policy(agent0base_policy) {
  # custom policy
}

agent0 = hyperdrive.init_agent(my_policy)
```
