### ISSUE TITLE
ethpy: create hyperdrive pool from existing factory contract

### ISSUE THREAD

**Issue by wakamex** [delvtech/agent0#907]
[this commit](https://github.com/delvtech/elf-simulations/pull/879/commits/2b21763c3680ee7f94a8586ed01de29ee0c58835) shows an unfinished flow that passes in `contract_addresses` from an already deployed hyperdrive instance. I attempt to use the factory to deploy a new pool, but it fails. to succeed, it would also need to deploy a new yield source, which is currently bundled with the factory deployment.

**Comment by dpaiton** [comment]
InteractiveHyperdrive now supports this:
https://github.com/delvtech/agent0/blob/69e077cedfd097794cc53ee631ccd6a70f14c6f3/lib/agent0/examples/interactive_hyperdrive_example.py#L29
