### ISSUE TITLE
chainsync: update to use hyperdrivepy's get spot price

### ISSUE THREAD

**Issue by dpaiton** [delvtech/agent0#927]
Depends on #910 to be finished.

Chainsync needs to use the underlying hyperdrivepy functions for computing derived variables, such as fixed rate & spot price. HyperdriveInterface tends to want to do smart contract calls for state (pool_info, pool_config), so chainsync should lean more into hyperdrivepy and the other `ethpy/hyperdrive/interface` utilities for getting things like spot price.

**Comment by dpaiton** [comment]
per our discussion, we want to leave the interface alone and use the underlying ethpy.hyperdrive.interface and pyperdrive.get_spot_price functions. This requires that we sync everything up with pypechain types.

**Comment by dpaiton** [comment]
Other functions requested in #1166

**Comment by slundqui** [comment]
Fixed in https://github.com/delvtech/agent0/pull/1467
